# Generated by Django 4.2.11 on 2024-05-22 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_apps', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='user_apps.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.PositiveIntegerField(default=1)),
                ('appoinment_fees', models.PositiveIntegerField(default=1)),
                ('New', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_apps.patient')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_apps.carts')),
            ],
        ),
    ]
