# Generated by Django 4.2.11 on 2024-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hsptlity_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consulting_time',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
